UPDATE dbo.CurrentData SET HomeTeam = 'Colchester United' WHERE HomeTeam = 'Colchester'
UPDATE dbo.CurrentData SET AwayTeam = 'Colchester United' WHERE AwayTeam = 'Colchester'
UPDATE dbo.CurrentData SET HomeTeam = 'West Ham United' WHERE HomeTeam = 'West Ham'
UPDATE dbo.CurrentData SET AwayTeam = 'West Ham United' WHERE AwayTeam = 'West Ham'
UPDATE dbo.CurrentData SET HomeTeam = 'Scunthorpe United' WHERE HomeTeam = 'Scunthorpe'
UPDATE dbo.CurrentData SET AwayTeam = 'Scunthorpe United' WHERE AwayTeam = 'Scunthorpe'
UPDATE dbo.CurrentData SET HomeTeam = 'Norwich City' WHERE HomeTeam = 'Norwich'
UPDATE dbo.CurrentData SET AwayTeam = 'Norwich City' WHERE AwayTeam = 'Norwich'
UPDATE dbo.CurrentData SET HomeTeam = 'Crewe Alexandra' WHERE HomeTeam = 'Crewe'
UPDATE dbo.CurrentData SET AwayTeam = 'Crewe Alexandra' WHERE AwayTeam = 'Crewe'
UPDATE dbo.CurrentData SET HomeTeam = 'Wolverhampton Wanderers' WHERE HomeTeam = 'Wolves'
UPDATE dbo.CurrentData SET AwayTeam = 'Wolverhampton Wanderers' WHERE AwayTeam = 'Wolves'
UPDATE dbo.CurrentData SET HomeTeam = 'Stockport County' WHERE HomeTeam = 'Stockport'
UPDATE dbo.CurrentData SET AwayTeam = 'Stockport County' WHERE AwayTeam = 'Stockport'
UPDATE dbo.CurrentData SET HomeTeam = 'Hartlepool United' WHERE HomeTeam = 'Hartlepool'
UPDATE dbo.CurrentData SET AwayTeam = 'Hartlepool United' WHERE AwayTeam = 'Hartlepool'
UPDATE dbo.CurrentData SET HomeTeam = 'Cambridge United' WHERE HomeTeam = 'Cambridge U'
UPDATE dbo.CurrentData SET AwayTeam = 'Cambridge United' WHERE AwayTeam = 'Cambridge U'
UPDATE dbo.CurrentData SET HomeTeam = 'Hereford United' WHERE HomeTeam = 'Hereford'
UPDATE dbo.CurrentData SET AwayTeam = 'Hereford United' WHERE AwayTeam = 'Hereford'
UPDATE dbo.CurrentData SET HomeTeam = 'Grimsby Town' WHERE HomeTeam = 'Grimsby'
UPDATE dbo.CurrentData SET AwayTeam = 'Grimsby Town' WHERE AwayTeam = 'Grimsby'
UPDATE dbo.CurrentData SET HomeTeam = 'Nottingham Forest' WHERE HomeTeam = 'Nottm Forest'
UPDATE dbo.CurrentData SET AwayTeam = 'Nottingham Forest' WHERE AwayTeam = 'Nottm Forest'
UPDATE dbo.CurrentData SET HomeTeam = 'Derby County' WHERE HomeTeam = 'Derby'
UPDATE dbo.CurrentData SET AwayTeam = 'Derby County' WHERE AwayTeam = 'Derby'
UPDATE dbo.CurrentData SET HomeTeam = 'Sheffield Wednesday' WHERE HomeTeam = 'Sheff Wed'
UPDATE dbo.CurrentData SET AwayTeam = 'Sheffield Wednesday' WHERE AwayTeam = 'Sheff Wed'
UPDATE dbo.CurrentData SET HomeTeam = 'Wigan Athletic' WHERE HomeTeam = 'Wigan'
UPDATE dbo.CurrentData SET AwayTeam = 'Wigan Athletic' WHERE AwayTeam = 'Wigan'
UPDATE dbo.CurrentData SET HomeTeam = 'Cardiff City' WHERE HomeTeam = 'Cardiff'
UPDATE dbo.CurrentData SET AwayTeam = 'Cardiff City' WHERE AwayTeam = 'Cardiff'
UPDATE dbo.CurrentData SET HomeTeam = 'Coventry City' WHERE HomeTeam = 'Coventry'
UPDATE dbo.CurrentData SET AwayTeam = 'Coventry City' WHERE AwayTeam = 'Coventry'
UPDATE dbo.CurrentData SET HomeTeam = 'York City' WHERE HomeTeam = 'York'
UPDATE dbo.CurrentData SET AwayTeam = 'York City' WHERE AwayTeam = 'York'
UPDATE dbo.CurrentData SET HomeTeam = 'Exeter City' WHERE HomeTeam = 'Exeter'
UPDATE dbo.CurrentData SET AwayTeam = 'Exeter City' WHERE AwayTeam = 'Exeter'
UPDATE dbo.CurrentData SET HomeTeam = 'Manchester City' WHERE HomeTeam = 'Man City'
UPDATE dbo.CurrentData SET AwayTeam = 'Manchester City' WHERE AwayTeam = 'Man City'
UPDATE dbo.CurrentData SET HomeTeam = 'Manchester United' WHERE HomeTeam = 'Man Utd'
UPDATE dbo.CurrentData SET AwayTeam = 'Manchester United' WHERE AwayTeam = 'Man Utd'
UPDATE dbo.CurrentData SET HomeTeam = 'Torquay United' WHERE HomeTeam = 'Torquay'
UPDATE dbo.CurrentData SET AwayTeam = 'Torquay United' WHERE AwayTeam = 'Torquay'
UPDATE dbo.CurrentData SET HomeTeam = 'Rotherham United' WHERE HomeTeam = 'Rotherham'
UPDATE dbo.CurrentData SET AwayTeam = 'Rotherham United' WHERE AwayTeam = 'Rotherham'
UPDATE dbo.CurrentData SET HomeTeam = 'Peterborough United' WHERE HomeTeam = 'Peterborough'
UPDATE dbo.CurrentData SET AwayTeam = 'Peterborough United' WHERE AwayTeam = 'Peterborough'
UPDATE dbo.CurrentData SET HomeTeam = 'Tranmere Rovers' WHERE HomeTeam = 'Tranmere'
UPDATE dbo.CurrentData SET AwayTeam = 'Tranmere Rovers' WHERE AwayTeam = 'Tranmere'
UPDATE dbo.CurrentData SET HomeTeam = 'Blackburn Rovers' WHERE HomeTeam = 'Blackburn'
UPDATE dbo.CurrentData SET AwayTeam = 'Blackburn Rovers' WHERE AwayTeam = 'Blackburn'
UPDATE dbo.CurrentData SET HomeTeam = 'Halifax Town' WHERE HomeTeam = 'Halifax'
UPDATE dbo.CurrentData SET AwayTeam = 'Halifax Town' WHERE AwayTeam = 'Halifax'
UPDATE dbo.CurrentData SET HomeTeam = 'Darlington' WHERE HomeTeam = 'Darlington (old)'
UPDATE dbo.CurrentData SET AwayTeam = 'Darlington' WHERE AwayTeam = 'Darlington (old)'
UPDATE dbo.CurrentData SET HomeTeam = 'Luton Town' WHERE HomeTeam = 'Luton'
UPDATE dbo.CurrentData SET AwayTeam = 'Luton Town' WHERE AwayTeam = 'Luton'
UPDATE dbo.CurrentData SET HomeTeam = 'Ipswich Town' WHERE HomeTeam = 'Ipswich'
UPDATE dbo.CurrentData SET AwayTeam = 'Ipswich Town' WHERE AwayTeam = 'Ipswich'
UPDATE dbo.CurrentData SET HomeTeam = 'Tottenham Hotspur' WHERE HomeTeam = 'Tottenham'
UPDATE dbo.CurrentData SET AwayTeam = 'Tottenham Hotspur' WHERE AwayTeam = 'Tottenham'
UPDATE dbo.CurrentData SET HomeTeam = 'West Bromwich Albion' WHERE HomeTeam = 'West Brom'
UPDATE dbo.CurrentData SET AwayTeam = 'West Bromwich Albion' WHERE AwayTeam = 'West Brom'
UPDATE dbo.CurrentData SET HomeTeam = 'Middlesbrough' WHERE HomeTeam = 'Middlesbro'
UPDATE dbo.CurrentData SET AwayTeam = 'Middlesbrough' WHERE AwayTeam = 'Middlesbro'
UPDATE dbo.CurrentData SET HomeTeam = 'Hull City' WHERE HomeTeam = 'Hull'
UPDATE dbo.CurrentData SET AwayTeam = 'Hull City' WHERE AwayTeam = 'Hull'
UPDATE dbo.CurrentData SET HomeTeam = 'Stoke City' WHERE HomeTeam = 'Stoke'
UPDATE dbo.CurrentData SET AwayTeam = 'Stoke City' WHERE AwayTeam = 'Stoke'
UPDATE dbo.CurrentData SET HomeTeam = 'Birmingham City' WHERE HomeTeam = 'Birmingham'
UPDATE dbo.CurrentData SET AwayTeam = 'Birmingham City' WHERE AwayTeam = 'Birmingham'
UPDATE dbo.CurrentData SET HomeTeam = 'Leeds United' WHERE HomeTeam = 'Leeds'
UPDATE dbo.CurrentData SET AwayTeam = 'Leeds United' WHERE AwayTeam = 'Leeds'
UPDATE dbo.CurrentData SET HomeTeam = 'Newcastle United' WHERE HomeTeam = 'Newcastle'
UPDATE dbo.CurrentData SET AwayTeam = 'Newcastle United' WHERE AwayTeam = 'Newcastle'
UPDATE dbo.CurrentData SET HomeTeam = 'Carlisle United' WHERE HomeTeam = 'Carlisle'
UPDATE dbo.CurrentData SET AwayTeam = 'Carlisle United' WHERE AwayTeam = 'Carlisle'
UPDATE dbo.CurrentData SET HomeTeam = 'Crystal Palace' WHERE HomeTeam = 'C Palace'
UPDATE dbo.CurrentData SET AwayTeam = 'Crystal Palace' WHERE AwayTeam = 'C Palace'
UPDATE dbo.CurrentData SET HomeTeam = 'Oxford United' WHERE HomeTeam = 'Oxford'
UPDATE dbo.CurrentData SET AwayTeam = 'Oxford United' WHERE AwayTeam = 'Oxford'
UPDATE dbo.CurrentData SET HomeTeam = 'Swindon Town' WHERE HomeTeam = 'Swindon'
UPDATE dbo.CurrentData SET AwayTeam = 'Swindon Town' WHERE AwayTeam = 'Swindon'
UPDATE dbo.CurrentData SET HomeTeam = 'Brighton and Hove Albion' WHERE HomeTeam = 'Brighton'
UPDATE dbo.CurrentData SET AwayTeam = 'Brighton and Hove Albion' WHERE AwayTeam = 'Brighton'
UPDATE dbo.CurrentData SET HomeTeam = 'AFC Bournemouth' WHERE HomeTeam = 'Bournemouth'
UPDATE dbo.CurrentData SET AwayTeam = 'AFC Bournemouth' WHERE AwayTeam = 'Bournemouth'
UPDATE dbo.CurrentData SET HomeTeam = 'Shrewsbury Town' WHERE HomeTeam = 'Shrewsbury'
UPDATE dbo.CurrentData SET AwayTeam = 'Shrewsbury Town' WHERE AwayTeam = 'Shrewsbury'
UPDATE dbo.CurrentData SET HomeTeam = 'Plymouth Argyle' WHERE HomeTeam = 'Plymouth'
UPDATE dbo.CurrentData SET AwayTeam = 'Plymouth Argyle' WHERE AwayTeam = 'Plymouth'
UPDATE dbo.CurrentData SET HomeTeam = 'Charlton Athletic' WHERE HomeTeam = 'Charlton'
UPDATE dbo.CurrentData SET AwayTeam = 'Charlton Athletic' WHERE AwayTeam = 'Charlton'
UPDATE dbo.CurrentData SET HomeTeam = 'Bradford City' WHERE HomeTeam = 'Bradford'
UPDATE dbo.CurrentData SET AwayTeam = 'Bradford City' WHERE AwayTeam = 'Bradford'
UPDATE dbo.CurrentData SET HomeTeam = 'Oldham Athletic' WHERE HomeTeam = 'Oldham'
UPDATE dbo.CurrentData SET AwayTeam = 'Oldham Athletic' WHERE AwayTeam = 'Oldham'
UPDATE dbo.CurrentData SET HomeTeam = 'Huddersfield Town' WHERE HomeTeam = 'Huddersfield'
UPDATE dbo.CurrentData SET AwayTeam = 'Huddersfield Town' WHERE AwayTeam = 'Huddersfield'
UPDATE dbo.CurrentData SET HomeTeam = 'Preston North End' WHERE HomeTeam = 'Preston'
UPDATE dbo.CurrentData SET AwayTeam = 'Preston North End' WHERE AwayTeam = 'Preston'
UPDATE dbo.CurrentData SET HomeTeam = 'Northampton Town' WHERE HomeTeam = 'Northampton'
UPDATE dbo.CurrentData SET AwayTeam = 'Northampton Town' WHERE AwayTeam = 'Northampton'
UPDATE dbo.CurrentData SET HomeTeam = 'Southend United' WHERE HomeTeam = 'Southend'
UPDATE dbo.CurrentData SET AwayTeam = 'Southend United' WHERE AwayTeam = 'Southend'
UPDATE dbo.CurrentData SET HomeTeam = 'Aldershot Town' WHERE HomeTeam = 'Aldershot'
UPDATE dbo.CurrentData SET AwayTeam = 'Aldershot Town' WHERE AwayTeam = 'Aldershot'
UPDATE dbo.CurrentData SET HomeTeam = 'Leicester City' WHERE HomeTeam = 'Leicester'
UPDATE dbo.CurrentData SET AwayTeam = 'Leicester City' WHERE AwayTeam = 'Leicester'
UPDATE dbo.CurrentData SET HomeTeam = 'Bristol City' WHERE HomeTeam = 'Bristol C'
UPDATE dbo.CurrentData SET AwayTeam = 'Bristol City' WHERE AwayTeam = 'Bristol C'
UPDATE dbo.CurrentData SET HomeTeam = 'Bristol Rovers' WHERE HomeTeam = 'Bristol R'
UPDATE dbo.CurrentData SET AwayTeam = 'Bristol Rovers' WHERE AwayTeam = 'Bristol R'
UPDATE dbo.CurrentData SET HomeTeam = 'Swansea City' WHERE HomeTeam = 'Swansea'
UPDATE dbo.CurrentData SET AwayTeam = 'Swansea City' WHERE AwayTeam = 'Swansea'
UPDATE dbo.CurrentData SET HomeTeam = 'Bolton Wanderers' WHERE HomeTeam = 'Bolton'
UPDATE dbo.CurrentData SET AwayTeam = 'Bolton Wanderers' WHERE AwayTeam = 'Bolton'
UPDATE dbo.CurrentData SET HomeTeam = 'Lincoln City' WHERE HomeTeam = 'Lincoln'
UPDATE dbo.CurrentData SET AwayTeam = 'Lincoln City' WHERE AwayTeam = 'Lincoln'
UPDATE dbo.CurrentData SET HomeTeam = 'Doncaster Rovers' WHERE HomeTeam = 'Doncaster'
UPDATE dbo.CurrentData SET AwayTeam = 'Doncaster Rovers' WHERE AwayTeam = 'Doncaster'
UPDATE dbo.CurrentData SET HomeTeam = 'Notts County' WHERE HomeTeam = 'Notts Co'
UPDATE dbo.CurrentData SET AwayTeam = 'Notts County' WHERE AwayTeam = 'Notts Co'
UPDATE dbo.CurrentData SET HomeTeam = 'Sheffield United' WHERE HomeTeam = 'Sheff Utd'
UPDATE dbo.CurrentData SET AwayTeam = 'Sheffield United' WHERE AwayTeam = 'Sheff Utd'
UPDATE dbo.CurrentData SET HomeTeam = 'Chester City' WHERE HomeTeam = 'Chester'
UPDATE dbo.CurrentData SET AwayTeam = 'Chester City' WHERE AwayTeam = 'Chester'
UPDATE dbo.CurrentData SET HomeTeam = 'Mansfield Town' WHERE HomeTeam = 'Mansfield'
UPDATE dbo.CurrentData SET AwayTeam = 'Mansfield Town' WHERE AwayTeam = 'Mansfield'
UPDATE dbo.CurrentData SET HomeTeam = 'Newport County' WHERE HomeTeam = 'Newport C (old)'
UPDATE dbo.CurrentData SET AwayTeam = 'Newport County' WHERE AwayTeam = 'Newport C (old)'
UPDATE dbo.CurrentData SET HomeTeam = 'Bradford Park Avenue' WHERE HomeTeam = 'Bradford PA'
UPDATE dbo.CurrentData SET AwayTeam = 'Bradford Park Avenue' WHERE AwayTeam = 'Bradford PA'
UPDATE dbo.CurrentData SET HomeTeam = 'Accrington Stanley' WHERE HomeTeam = 'Accrington'
UPDATE dbo.CurrentData SET AwayTeam = 'Accrington Stanley' WHERE AwayTeam = 'Accrington'
UPDATE dbo.CurrentData SET HomeTeam = 'Merthyr Town' WHERE HomeTeam = 'Merthyr T (old)'
UPDATE dbo.CurrentData SET AwayTeam = 'Merthyr Town' WHERE AwayTeam = 'Merthyr T (old)'
UPDATE dbo.CurrentData SET HomeTeam = 'Aberdare Athletic' WHERE HomeTeam = 'Aberdare Ath.'
UPDATE dbo.CurrentData SET AwayTeam = 'Aberdare Athletic' WHERE AwayTeam = 'Aberdare Ath.'
UPDATE dbo.CurrentData SET HomeTeam = 'Stalybridge Celtic' WHERE HomeTeam = 'Stalybridge'
UPDATE dbo.CurrentData SET AwayTeam = 'Stalybridge Celtic' WHERE AwayTeam = 'Stalybridge'
UPDATE dbo.CurrentData SET HomeTeam = 'Glossop North End' WHERE HomeTeam = 'Glossop'
UPDATE dbo.CurrentData SET AwayTeam = 'Glossop North End' WHERE AwayTeam = 'Glossop'
UPDATE dbo.CurrentData SET HomeTeam = 'Gainsborough Trinity' WHERE HomeTeam = 'Gainsborough'
UPDATE dbo.CurrentData SET AwayTeam = 'Gainsborough Trinity' WHERE AwayTeam = 'Gainsborough'
UPDATE dbo.CurrentData SET HomeTeam = 'New Brighton Tower' WHERE HomeTeam = 'New Brighton T'
UPDATE dbo.CurrentData SET AwayTeam = 'New Brighton Tower' WHERE AwayTeam = 'New Brighton T'
UPDATE dbo.CurrentData SET HomeTeam = 'Loughborough' WHERE HomeTeam = 'Loughbr''gh Dy'
UPDATE dbo.CurrentData SET AwayTeam = 'Loughborough' WHERE AwayTeam = 'Loughbr''gh Dy'
UPDATE dbo.CurrentData SET HomeTeam = 'Burton Wanderers' WHERE HomeTeam = 'Burton W'
UPDATE dbo.CurrentData SET AwayTeam = 'Burton Wanderers' WHERE AwayTeam = 'Burton W'
UPDATE dbo.CurrentData SET HomeTeam = 'Northwich Victoria' WHERE HomeTeam = 'Northwich'
UPDATE dbo.CurrentData SET AwayTeam = 'Northwich Victoria' WHERE AwayTeam = 'Northwich'
UPDATE dbo.CurrentData SET HomeTeam = 'Middlesbrough Ironopolis' WHERE HomeTeam = 'Middlsbro Irn'
UPDATE dbo.CurrentData SET AwayTeam = 'Middlesbrough Ironopolis' WHERE AwayTeam = 'Middlsbro Irn'
UPDATE dbo.CurrentData SET HomeTeam = 'Accrington' WHERE HomeTeam = 'Accrington (old)'
UPDATE dbo.CurrentData SET AwayTeam = 'Accrington' WHERE AwayTeam = 'Accrington (old)'
